version: '2'
services:
    jwtgateway-app:
        image: jwtgateway
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jwtgateway-mysql:3306/jwtgateway?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8087:8087
    jwtgateway-mysql:
        extends:
            file: mysql.yml
            service: jwtgateway-mysql
